global:
  smtp_smarthost: 'smtp-relay.brevo.com:587'
  smtp_from: 'contato@mateusdata.com.br'
  smtp_auth_username: '76f807001@smtp-brevo.com'
  smtp_auth_password: 'PQvRx9X4asdTFKM2'

receivers:
- name: 'email'
  email_configs:
  - to: 'mateuspele2015@gmail.com'
    send_resolved: true

route:
  receiver: 'email'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
